Update homolog.yml

diff --git a/.github/workflows/homolog.yml b/.github/workflows/homolog.yml
--- a/.github/workflows/homolog.yml
+++ b/.github/workflows/homolog.yml
@@ -1,11 +1,12 @@
-name: Deploy to Homolog
+name: Deploy to Production
 
 on:
   push:
     branches:
-      - homolog  # Trigger on push to the main branch (after merge)
+      - main  # Trigger on push to the main branch (after merge)
+
 jobs:
-  build_and_deploy:
+  Deploy:
     runs-on: ubuntu-latest
 
     steps:
@@ -19,51 +20,38 @@ jobs:
         with:
           php-version: '8.2'  # Adjust PHP version as required
 
-      # Install Composer dependencies
+      # Install Composer dependencies (optional, adjust if using Composer)
       - name: Install Composer dependencies
         run: |
           curl -sS https://getcomposer.org/installer | php
           php composer.phar install --no-interaction
       # Validate PHP code (Linting)
-      - name: Validate PHP code
-        run: |
-          find . -type f -name "*.php" -exec php -l {} \;
+      #- name: Validate PHP code
+        #run: |
+          #find . -type f -name "*.php" -exec php -l {} \;
 
       # Install lftp (alternative to ncftp for FTP upload)
       - name: Install lftp
-        run: sudo apt-get install -y lftp
+        run: sudo apt-get install -y lftp unzip zip sshpass
 
       # Prepare files for upload, respecting .gitignore
       - name: Prepare files for upload (ignore gitignored files)
         run: |
           # Get list of files tracked by git (ignoring .gitignore files)
           git ls-files --exclude-standard | tar -czf files_to_upload.tar.gz -T -
-      # Upload files via FTP using lftp (non-interactive)
-      - name: Upload files to FTP server (ignore SSL)
+      # Backup app
+      - name: Backupping App
         run: |
-<<<<<<< HEAD
-          # Extract the files and upload via lftp
-          mkdir -p /tmp/uploaded_files
-          tar -xzf files_to_upload.tar.gz -C /tmp/uploaded_files
-          rm /tmp/uploaded_files/config.inc.php
-          # Use lftp for the FTP connection and file upload
-          lftp -d -e "
-            set ssl:verify-certificate no;
-            open -u ${FTP_USERNAME},${FTP_PASSWORD} ${FTP_SERVER};
-            mirror -R /tmp/uploaded_files /;
-            bye
-          "
-        env:
-          FTP_SERVER: ${{ secrets.HOMOLOG_FTP_HOST }}
-          FTP_USERNAME: ${{ secrets.HOMOLOG_FTP_USERNAME }}
-          FTP_PASSWORD: ${{ secrets.HOMOLOG_FTP_PASSWORD }}
-=======
+          curl -L "https://deploy.clinabs.com.br/deploy.php?action=backup"
+          
+      # Upload files via FTP using lftp (non-interactive)
+      - name: Upload files to FTP server
+        run: |
           mkdir -p /tmp/uploaded_files
           tar -xzf files_to_upload.tar.gz -C /tmp/uploaded_files
           lftp -d -e "
             set ssl:verify-certificate no;
             open -u ${FTP_USERNAME},${FTP_PASSWORD} ${FTP_SERVER};
-            
             # Upload and rename files
             put -O / /tmp/uploaded_files/info/manutencao.php -o /manutencao.php;
             put -O / /tmp/uploaded_files/.busy -o /.htaccess;
@@ -72,10 +60,14 @@ jobs:
             mirror -R --exclude .busy --exclude .apache /tmp/uploaded_files /;
             put -O / /tmp/uploaded_files/.apache -o /.htaccess;
             bye
-          " 
-
+          "
+      - name: Check deployment success
+        run: |
+          if [ $? -ne 0 ]; then
+            echo "Deployment failed, triggering reverse deployment..."
+            curl -L "https://deploy.clinabs.com.br/deploy.php?action=reverse"
+          fi
         env:
-          FTP_SERVER: ${{ secrets.HOMOLOG_FTP_HOST }}
-          FTP_USERNAME: ${{ secrets.HOMOLOG_FTP_USERNAME }}
-          FTP_PASSWORD: ${{ secrets.HOMOLOG_FTP_PASSWORD }}
->>>>>>> homolog
+          FTP_SERVER: ${{ secrets.FTP_HOST }}
+          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
+          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
