fix:pipelines

diff --git a/.github/workflows/homolog.yml b/.github/workflows/homolog.yml
--- a/.github/workflows/homolog.yml
+++ b/.github/workflows/homolog.yml
@@ -3,9 +3,13 @@ name: Deploy to Homolog
 on:
   push:
     branches:
-      - homolog  # Trigger on push to the main branch (after merge)
+      - homolog
 jobs:
+<<<<<<< HEAD
   Backup:
+=======
+  Deploy:
+>>>>>>> 198feb1a561c45d8b8cd687dd3cbac56de17ce30
     runs-on: ubuntu-latest
 
   Deploy:
@@ -26,51 +30,42 @@ jobs:
         with:
           php-version: '8.2'  # Adjust PHP version as required
 
-      # Install Composer dependencies
+      # Install Composer dependencies (optional, adjust if using Composer)
       - name: Install Composer dependencies
         run: |
           curl -sS https://getcomposer.org/installer | php
           php composer.phar install --no-interaction
       # Validate PHP code (Linting)
-      - name: Validate PHP code
-        run: |
-          find . -type f -name "*.php" -exec php -l {} \;
+      #- name: Validate PHP code
+        #run: |
+          #find . -type f -name "*.php" -exec php -l {} \;
 
       # Install lftp (alternative to ncftp for FTP upload)
       - name: Install lftp
-        run: sudo apt-get install -y lftp
+        run: sudo apt-get install -y lftp unzip zip sshpass
 
       # Prepare files for upload, respecting .gitignore
       - name: Prepare files for upload (ignore gitignored files)
         run: |
           # Get list of files tracked by git (ignoring .gitignore files)
           git ls-files --exclude-standard | tar -czf files_to_upload.tar.gz -T -
-      # Upload files via FTP using lftp (non-interactive)
-      - name: Upload files to FTP server (ignore SSL)
+      # Backup app
+      - name: Backupping App
         run: |
+          curl -L "https://deploy.clinabs.com.br/deploy.php?action=backup"
+          
+      # Upload files via FTP using lftp (non-interactive)
+      - name: Upload files to FTP server
+        run: |
+          mkdir -p /tmp/uploaded_files
+          tar -xzf files_to_upload.tar.gz -C /tmp/uploaded_files
+          lftp -d -e "
+            set ssl:verify-certificate no;
+            open -u ${FTP_USERNAME},${FTP_PASSWORD} ${FTP_SERVER};
 <<<<<<< HEAD
-          # Extract the files and upload via lftp
-          mkdir -p /tmp/uploaded_files
-          tar -xzf files_to_upload.tar.gz -C /tmp/uploaded_files
-          rm /tmp/uploaded_files/config.inc.php
-          # Use lftp for the FTP connection and file upload
-          lftp -d -e "
-            set ssl:verify-certificate no;
-            open -u ${FTP_USERNAME},${FTP_PASSWORD} ${FTP_SERVER};
-            mirror -R /tmp/uploaded_files /;
-            bye
-          "
-        env:
-          FTP_SERVER: ${{ secrets.HOMOLOG_FTP_HOST }}
-          FTP_USERNAME: ${{ secrets.HOMOLOG_FTP_USERNAME }}
-          FTP_PASSWORD: ${{ secrets.HOMOLOG_FTP_PASSWORD }}
-=======
-          mkdir -p /tmp/uploaded_files
-          tar -xzf files_to_upload.tar.gz -C /tmp/uploaded_files
-          lftp -d -e "
-            set ssl:verify-certificate no;
-            open -u ${FTP_USERNAME},${FTP_PASSWORD} ${FTP_SERVER};
             glob -v rm -r -- !(data|tmp|config.inc.php)
+=======
+>>>>>>> 198feb1a561c45d8b8cd687dd3cbac56de17ce30
             # Upload and rename files
             put -O / /tmp/uploaded_files/info/manutencao.php -o /manutencao.php;
             put -O / /tmp/uploaded_files/.busy -o /.htaccess;
@@ -79,10 +74,14 @@ jobs:
             mirror -R --exclude .busy --exclude .apache /tmp/uploaded_files /;
             put -O / /tmp/uploaded_files/.apache -o /.htaccess;
             bye
-          " 
-
+          "
+      - name: Check deployment success
+        run: |
+          if [ $? -ne 0 ]; then
+            echo "Deployment failed, triggering reverse deployment..."
+            curl -L "https://deploy.clinabs.com.br/deploy.php?action=reverse"
+          fi
         env:
           FTP_SERVER: ${{ secrets.HOMOLOG_FTP_HOST }}
           FTP_USERNAME: ${{ secrets.HOMOLOG_FTP_USERNAME }}
           FTP_PASSWORD: ${{ secrets.HOMOLOG_FTP_PASSWORD }}
->>>>>>> homolog
